phoenix-shopping/src/main/java/com/apd/phoenix/shopping/view/jsf/bean/HomeBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.apd.phoenix.shopping.view.jsf.bean;

import com.apd.phoenix.shopping.view.jsf.bean.search.Product;
import com.apd.phoenix.shopping.view.jsf.bean.search.SearchUtilities;
import com.apd.phoenix.shopping.view.jsf.bean.search.SolrSearcher;
import com.apd.phoenix.shopping.view.jsf.bean.utils.LinksBean;
import com.apd.phoenix.core.PageNumberDisplay;
import com.apd.phoenix.core.PageNumberDisplay.PageSize;
import com.apd.phoenix.service.solr.SolrServiceBean;
import com.apd.phoenix.shopping.view.jsf.bean.search.SolrQueryUtilities;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import javax.annotation.PostConstruct;
import javax.ejb.LocalBean;
import javax.ejb.Stateful;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.apache.solr.client.solrj.SolrQuery;
import org.apache.solr.client.solrj.SolrServer;
import org.apache.solr.client.solrj.SolrServerException;
import org.apache.solr.client.solrj.response.QueryResponse;
import org.apache.solr.common.SolrDocumentList;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author dcnorris
 */
@Named
@Stateful
@LocalBean
//TODO consider converting this to conversation scope
@SessionScoped
public class HomeBean implements SolrSearcher, Serializable {

    private static final long serialVersionUID = 1L;
    @Inject
    private LinksBean linksBean;
    private static final Logger logger = LoggerFactory.getLogger(HomeBean.class);
    private List<Product> featuredProductList = new ArrayList<>();
    private QueryResponse response;
    private SolrServer solr;
    private SolrQuery previousSolrQuery;
    private int previousPage;
    private PageNumberDisplay pageDisplay;
    private int numFound;
    private PageNumberDisplay.PageSize pageSize = PageNumberDisplay.PageSize.FOUR;
    @Inject
    private SolrQueryUtilities solrQueryUtilities;
    @Inject
    private SolrServiceBean solrServiceBean;

    @PostConstruct
    public void init() {
        try {
            solr = solrServiceBean.getSolrServer();
            SolrQuery solrQuery = new SolrQuery();
            solrQuery = solrQueryUtilities.addFilterByCatalogID(solrQuery);
            solrQuery.setStart(pageSize.toInt());
            solrQuery.setRows(pageSize.toInt());
            String startRange = "[" + "NOW-99YEARS" + " TO " + "NOW" + "]";
            solrQuery.add("q", "coreitemstartdate:" + startRange);
            String expireRange = "[" + "NOW+1DAY" + " TO " + "NOW+99YEARS" + "]";
            solrQuery.add("q", "coreitemexpirationdate:" + expireRange);
            Random rand = new Random();
            int value = rand.nextInt(99999);
            solrQuery.addSort("random_" + value, SolrQuery.ORDER.asc);
            response = solr.query(solrQuery);
            numFound = (int) response.getResults().getNumFound();
            previousSolrQuery = solrQuery;
            SolrDocumentList searchResultDocuments = response.getResults();
            featuredProductList = SearchUtilities.convertToProductList(searchResultDocuments);
            pageDisplay = new PageNumberDisplay(numFound);
            pageDisplay.setPageSize(pageSize);
        } catch (SolrServerException ex) {
            logger.error("Error attempting to Query Solr Index Server", ex);
        }
    }
    
    public List<Product> getFeaturedProductList() {
        if (pageDisplay.getPage() != previousPage) {
            try {
                previousPage = pageDisplay.getPage();
                previousSolrQuery.setStart((pageDisplay.getPage() - 1) * pageDisplay.getSize());
                QueryResponse updatedResponse = solr.query(previousSolrQuery);
                SolrDocumentList updatedDocList = updatedResponse.getResults();
                featuredProductList = SearchUtilities.convertToProductList(updatedDocList);
            } catch (SolrServerException ex) {
                logger.error("Error sending query to solr", ex);
            }
        }
        return featuredProductList;
    }

    public PageSize getPageSize() {
        return pageSize;
    }

    public void setPageSize(PageSize pageSize) {
        this.pageSize = pageSize;
    }

    public int getPreviousPage() {
        return previousPage;
    }

    public void setPreviousPage(int previousPage) {
        this.previousPage = previousPage;
    }

    public PageNumberDisplay getPageDisplay() {
        return pageDisplay;
    }

    public void setPageDisplay(PageNumberDisplay pageDisplay) {
        this.pageDisplay = pageDisplay;
    }

    public String getFavoritesManagementLink() {
        return linksBean.getUserFavorites()+"?showList=true";
    }

}

phoenix-shopping/src/main/java/com/apd/phoenix/shopping/view/jsf/bean/MarketingImagesBean.java
package com.apd.phoenix.shopping.view.jsf.bean;

import com.apd.phoenix.core.StringEscape;
import com.apd.phoenix.core.utility.PropertiesLoader;
import com.apd.phoenix.service.integration.cxml.model.catalog.Credential;
import com.apd.phoenix.service.model.CredentialPropertyType.CredentialPropertyTypeEnum;
import com.apd.phoenix.service.model.CredentialXCredentialPropertyType;
import com.apd.phoenix.shopping.view.jsf.bean.login.CredentialSelectionBean;
import javax.inject.Inject;
import javax.inject.Named;
import org.apache.commons.lang.StringUtils;

/**
 *
 * @author anicholson
 */
@Named
public class MarketingImagesBean {

    private static final String STATIC_CONTENT_URL = PropertiesLoader.getAsProperties("aws.integration").getProperty(
            "content.service.secure.domain");
    private static final String IMAGE_DIRECTORY = "/images/marketing/";
    private static final String IMAGE_DIRECTORY_URL = STATIC_CONTENT_URL + IMAGE_DIRECTORY;

    private static final String PROPERTIES_PREFIX = "image.name.";

    @Inject
    CredentialSelectionBean credentialSelectionBean;

    public String getBannerUrl() {
        if (credentialSelectionBean.getCurrentCredential() != null
                && credentialSelectionBean.getCurrentCredential().getProperties() != null) {
            String bannerName = findBannerName(credentialSelectionBean.getCurrentCredential());
            if (StringUtils.isNotEmpty(bannerName)) {
                return IMAGE_DIRECTORY_URL + StringEscape.escapeForUrl(bannerName);
            }
        }
        return getImageUrl("banner");
    }

    private String findBannerName(com.apd.phoenix.service.model.Credential currentCredential) {
        for (CredentialXCredentialPropertyType credentialPropety : currentCredential.getProperties()) {
            if (credentialPropety.getType() != null
                    && CredentialPropertyTypeEnum.BANNER_NAME.getValue().equals(credentialPropety.getType().getName())) {
                return credentialPropety.getValue();
            }
        }
        return null;
    }

    public static String getImageUrl(String location) {
        String imageName = PropertiesLoader.getAsProperties("themeMap.properties").getProperty(
                PROPERTIES_PREFIX + location);
        String url = IMAGE_DIRECTORY_URL + StringEscape.escapeForUrl(imageName);
        return url;
    }

}

phoenix-shopping/src/main/java/com/apd/phoenix/shopping/view/jsf/bean/PageCssBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.apd.phoenix.shopping.view.jsf.bean;

import com.apd.phoenix.core.StringEscape;
import java.io.Serializable;
import java.util.Properties;
import javax.ejb.Stateful;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.component.UIInput;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;
import org.apache.commons.lang.StringUtils;
import com.apd.phoenix.core.utility.EcommercePropertiesLoader;
import com.apd.phoenix.core.utility.PropertiesLoader;
import com.apd.phoenix.service.business.AccountBp;
import com.apd.phoenix.service.business.IpSubdomainRestriction;

/**
 * This class is used by the ecommerceMainTemplate.xthml template page to get
 * the appropriate css file for a specific customer.
 * <br /><br />
 * To set a CSS file for a particular account, save the file in
 * phoenix-shopping/src/main/webapp/resources/css/main, then add a property to
 * cssMap.properties and cssMapResponsive.properties, from the root account name
 * to the path of the CSS file.
 *
 * @author RHC
 *
 */
@Named
@Stateful
@RequestScoped
public class PageCssBean implements Serializable {

    private static final long serialVersionUID = 1L;
    private static String STATIC_CONTENT_URL = PropertiesLoader.getAsProperties("aws.integration").getProperty(
            "content.service.secure.domain");
    private static String CUSTOM_CSS_URL = STATIC_CONTENT_URL + "/phoenix-css/";
    public static String SUBDOMAIN_IMAGES = STATIC_CONTENT_URL + "/images/";
    public static String SUBDOMAIN_WELCOME_IMAGES = SUBDOMAIN_IMAGES + "welcome-images/";
    public static String SUBDOMAIN_LOGOS = SUBDOMAIN_IMAGES + "logos/";

    private static final String SUBDOMAIN_CSS_LOCATION = "css/subDomain/";
    private static final String CSS_FILE_EXTENSION = ".css";

    private static final String DEFAULT_CUSTOMER_SERVICE = "Customer Service: 800-849-5842 | sales@americanproduct.com";
    private static final String DEFAULT_PHONE = "800-849-5842";
    private static final String DEFAULT_DAYS = "Monday-Friday";
    private static final String DEFAULT_HRS = "8:00 am-8:00 pm est";
    private static final String DEFAULT_EMAIL = "sales@americanproduct.com";
    private static final String DEFAULT_WELCOME_IMAGE = "default.png";
    private static final String DEFAULT_VISIT_US_URL = "http://www.americanproduct.com";
    private static final String DEFAULT_VISIT_US_URL_TO_DISPLAY = "www.AmericanProduct.com";
    private static final String DEFAULT_FACEBOOK = "http://www.facebook.com/americanproduct";
    private static final String DEFAULT_LINKEDIN = "http://www.linkedin.com/company/american-product-distributors-inc-";
    private static final String DEFAULT_YOUTUBE = "http://www.youtube.com/user/TheAPDStory";
    private static final String DEFAULT_WORDPRESS = "http://americanproduct.wordpress.com/";
    private static final String DEFAULT_COPYRIGHT = "Copyright 2015 American Product Distributors Inc.";

    @Inject
    private AccountBp accountBp;

    public String getSubDomainBasedCssFile() {
        String cssKey = getSubdomainValue();
        if (cssKey.isEmpty() || cssKey.equals(IpSubdomainRestriction.GENERIC_SUBDOMAIN)) {
            return "";
        }
        return CUSTOM_CSS_URL + SUBDOMAIN_CSS_LOCATION + StringEscape.escapeForUrl(cssKey) + CSS_FILE_EXTENSION;
    }

    public String getSubdomainValue() {
        HttpServletRequest request = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext()
                .getRequest();
        return IpSubdomainRestriction.ipAndSubdomain(request)[1];
    }

    public String getSubDomainWelcomeMessage() {
        return this.getSubdomainSpecificProperty("_WelcomMessage", "");
    }

    public String getSubDomainWelcomeMessageHeader() {
        return this.getSubdomainSpecificProperty("_WelcomMessageHeader", "");
    }

    public String getSubDomainWelcomeImage() {
        return SUBDOMAIN_WELCOME_IMAGES + this.getSubdomainSpecificProperty("_WelcomeImage", DEFAULT_WELCOME_IMAGE);
    }

    public String getSubDomainLogo() {
        String imageName = this.getSubdomainSpecificProperty("_Logo", "");
        if (StringUtils.isNotEmpty(imageName)) {
            return SUBDOMAIN_LOGOS + imageName;
        }
        else {
            return "";
        }
    }

    public String getCustomerServiceInfo() {
        return this.getSubdomainSpecificProperty("_customerServiceInfo", DEFAULT_CUSTOMER_SERVICE);
    }

    public String getCallUsPhone() {
        return this.getSubdomainSpecificProperty("_callUsPhone", DEFAULT_PHONE);
    }

    public String getCallUsDays() {
        return this.getSubdomainSpecificProperty("_callUsDays", DEFAULT_DAYS);
    }

    public String getCallUsHrs() {
        return this.getSubdomainSpecificProperty("_callUsHrs", DEFAULT_HRS);
    }

    public String getEmailUsAddress() {
        return this.getSubdomainSpecificProperty("_emailUsAddress", DEFAULT_EMAIL);
    }

    public String getVisitUsSite() {
        return this.getSubdomainSpecificProperty("_visitUsSite", DEFAULT_VISIT_US_URL);
    }

    public String getVisitUsSiteToDisplay() {
        return this.getSubdomainSpecificProperty("_visitUsSiteToDsiplay", DEFAULT_VISIT_US_URL_TO_DISPLAY);
    }

    public String getFaceBook() {
        return this.getSubdomainSpecificProperty("_facebook", DEFAULT_FACEBOOK);
    }

    public String getLinkedIn() {
        return this.getSubdomainSpecificProperty("_linkedin", DEFAULT_LINKEDIN);
    }

    public String getYouTube() {
        return this.getSubdomainSpecificProperty("_youtube", DEFAULT_YOUTUBE);
    }

    public String getWordPress() {
        return this.getSubdomainSpecificProperty("_wordpress", DEFAULT_WORDPRESS);
    }

    public String getCopyRight() {
        return this.getSubdomainSpecificProperty("_copyright", DEFAULT_COPYRIGHT);
    }

    private String getSubdomainSpecificProperty(String propertyName, String defaultValue) {
        String prefix = getSubdomainValue();
        String key = prefix + propertyName;
        Properties properties = PropertiesLoader.getAsProperties("themeMap");
        if (properties != null && properties.containsKey(key)) {
            return properties.getProperty(key, "");
        }
        else {
            return defaultValue;
        }
    }

    public void validateEmailDomain(FacesContext context, UIComponent component, Object value) {
        if (value != null && !accountBp.validEmailAddress(value.toString(), getSubdomainValue())) {
            ((UIInput) component).setValid(false);
            FacesMessage message = new FacesMessage();
            message.setSeverity(FacesMessage.SEVERITY_ERROR);
            message.setSummary(EcommercePropertiesLoader.getInstance().getEcommerceProperties().getString(
                    "registration.email.invalid.summary"));
            message.setDetail(EcommercePropertiesLoader.getInstance().getEcommerceProperties().getString(
                    "registration.email.invalid.detail"));
            context.addMessage(null, message);
        }
    }
}

phoenix-shopping/src/main/java/com/apd/phoenix/shopping/view/jsf/bean/cashout/AddToCartDemoBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.apd.phoenix.shopping.view.jsf.bean.cashout;

import com.apd.phoenix.service.model.Item;
import com.apd.phoenix.shopping.view.jsf.bean.data.MockDataFactory;
import com.google.gson.Gson;
import java.util.List;
import javax.ejb.Stateful;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author dcnorris
 */
@Named
@Stateful
@SessionScoped
public class AddToCartDemoBean {

    private ItemJsonContainer tempNotification;

    private static final Logger LOGGER = LoggerFactory.getLogger(AddToCartDemoBean.class);

    public String addSelectedItemsToCart() {
        StringBuilder jsonResponse = new StringBuilder();
        jsonResponse.append("[");
        List<Item> items = MockDataFactory.ItemFactory.getItemList(2);

        jsonResponse.append(getJSON(items.get(0), "hardSubstitute"));
        jsonResponse.append(",");
        jsonResponse.append(getJSON(items.get(1), "softSubstitute"));
        jsonResponse.append("]");
        LOGGER.info("Response: ");
        LOGGER.info(jsonResponse.toString());
        return jsonResponse.toString();
    }

    private String getJSON(Item item, String type) {
        ItemJsonContainer obj = new ItemJsonContainer();
        obj.setImgURL("/shopping/resources/img/image_placement/75x75");
        obj.setItemName(item.getName());
        obj.setItemPrice("3.99");
        obj.setItemQty("2");
        obj.setMessageHeader("Item Added Successfully!!!");

        Gson gson = new Gson();

        // convert java object to JSON format,
        // and returned as JSON formatted string
        String json = gson.toJson(obj);

        return json;
    }

    public void addToTempList() {
        //        notificationList.add(tempNotification);
        LOGGER.info("addToTempList Method Called");
    }

    public ItemJsonContainer getTempNotification() {
        return tempNotification;
    }

    public void setTempNotification(ItemJsonContainer tempNotification) {
        this.tempNotification = tempNotification;
    }

}

phoenix-shopping/src/main/webapp/400.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">

    <h:head>
        <title>Bad Request</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <h:outputStylesheet name="css/bootstrap/bootstrap.css" />
        <h:outputStylesheet name="css/bootstrap/bootstrap-responsive.css" />
        <h:outputStylesheet name="css/main/ecommerce.css" />
        <h:outputStylesheet name="css/main/ecommerce-responsive.css" />
        <h:outputStylesheet name="css/fonts/stylesheet.css" />
        <ui:include src="WEB-INF/templates/dynamicCss.xhtml" />
        <meta name="description" content=""/>
        <meta name="viewport" content="width=device-width"/>
    </h:head>
    <h:body>
    <div id="bodyWrapper">
        <div class="containerFull">
            <div class="apd-container">  
    			<h:form>
	                <div id="header" class="navbar navbar-fluid container">
	                    <a href="#{linksBean.home}"><img height="50" src="#{propertiesBean.get('aws.integration','content.service.secure.domain')}/images/APD-logo.png" width="201"/></a>
	                </div>
	                <h2>400</h2>
	                <p>We apologize for the inconvenience. <h:commandLink action="#{loginBean.logout}" value="Click here" /> to return to the login page. If this problem persists, please contact customer service at #{pageCssBean.callUsPhone}.</p>
				</h:form>
            </div>
        </div>
    </div>
    </h:body>
    <h:outputScript library="js" name="jquery-2.0.2.min.js" />
    <h:outputScript library="js" name="bootstrap.js" />
    <h:outputScript library="js" name="jquery.backstretch.min.js" />
    <!--          [if lt IE 9]>
                            <script src="/shopping/resources/js/html5shiv.js"></script>
                            <script src="/shopping/resources/js/html5shiv-printshiv.js"></script>
                    <![endif]
              
              [if lte IE 8]>
              <link rel="stylesheet" href="/shopping/resources/css/ie8_below.css">
              <![endif]-->
    <script>
        $.backstretch("#{propertiesBean.get('aws.integration','content.service.secure.domain')}/images/background/apd-Background.jpg");
    </script>
</html>

phoenix-shopping/src/main/webapp/403.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">

    <h:head>
        <title>Restricted</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <h:outputStylesheet name="css/bootstrap/bootstrap.css" />
        <h:outputStylesheet name="css/bootstrap/bootstrap-responsive.css" />
        <h:outputStylesheet name="css/main/ecommerce.css" />
        <h:outputStylesheet name="css/main/ecommerce-responsive.css" />
        <h:outputStylesheet name="css/fonts/stylesheet.css" />
        <ui:include src="WEB-INF/templates/dynamicCss.xhtml" />
        <meta name="description" content=""/>
        <meta name="viewport" content="width=device-width"/>
    </h:head>
    <h:body>
    <div id="bodyWrapper">
        <div class="containerFull">
            <div class="apd-container">  
                <div id="header" class="navbar navbar-fluid container">
                    <a href="#{linksBean.home}"><img height="50" src="#{propertiesBean.get('aws.integration','content.service.secure.domain')}/images/APD-logo.png" width="201"/></a>
                </div>
                <h2>403</h2>
                <p>This page is forbidden.</p>
            </div>
        </div>
	</div>
    </h:body>
    <h:outputScript library="js" name="jquery-2.0.2.min.js" />
    <h:outputScript library="js" name="bootstrap.js" />
    <h:outputScript library="js" name="jquery.backstretch.min.js" />
    <!--          [if lt IE 9]>
                            <script src="/shopping/resources/js/html5shiv.js"></script>
                            <script src="/shopping/resources/js/html5shiv-printshiv.js"></script>
                    <![endif]
              
              [if lte IE 8]>
              <link rel="stylesheet" href="/shopping/resources/css/ie8_below.css">
              <![endif]-->
    <script>
        $.backstretch("#{propertiesBean.get('aws.integration','content.service.secure.domain')}/images/background/apd-Background.jpg");
    </script>
</html>

phoenix-shopping/src/main/webapp/404.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">

    <h:head>
        <title>Wrong URL?</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <h:outputStylesheet name="css/bootstrap/bootstrap.css" />
        <h:outputStylesheet name="css/bootstrap/bootstrap-responsive.css" />
        <h:outputStylesheet name="css/main/ecommerce.css" />
        <h:outputStylesheet name="css/main/ecommerce-responsive.css" />
        <h:outputStylesheet name="css/fonts/stylesheet.css" />
        <ui:include src="WEB-INF/templates/dynamicCss.xhtml" />
        <meta name="description" content=""/>
        <meta name="viewport" content="width=device-width"/>
    </h:head>
    <h:body>
    <div id="bodyWrapper">
        <div class="containerFull">
            <div class="apd-container">  
                <div id="header" class="navbar navbar-fluid container">
                    <a href="#{linksBean.home}"><img height="50" src="#{propertiesBean.get('aws.integration','content.service.secure.domain')}/images/APD-logo.png" width="201"/></a>
                </div>
                <h2>404</h2>
                <p>The requested resource cannot be found.</p>
            </div>
        </div>
	</div>
    </h:body>
    <h:outputScript library="js" name="jquery-2.0.2.min.js" />
    <h:outputScript library="js" name="bootstrap.js" />
    <h:outputScript library="js" name="jquery.backstretch.min.js" />
    <!--          [if lt IE 9]>
                            <script src="/shopping/resources/js/html5shiv.js"></script>
                            <script src="/shopping/resources/js/html5shiv-printshiv.js"></script>
                    <![endif]
              
              [if lte IE 8]>
              <link rel="stylesheet" href="/shopping/resources/css/ie8_below.css">
              <![endif]-->
    <script>
        $.backstretch("#{propertiesBean.get('aws.integration','content.service.secure.domain')}/images/background/apd-Background.jpg");
    </script>
</html>