phoenix-shopping/src/main/java/com/apd/phoenix/shopping/view/jsf/bean/HomeBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.apd.phoenix.shopping.view.jsf.bean;

import com.apd.phoenix.shopping.view.jsf.bean.search.Product;
import com.apd.phoenix.shopping.view.jsf.bean.search.SearchUtilities;
import com.apd.phoenix.shopping.view.jsf.bean.search.SolrSearcher;
import com.apd.phoenix.shopping.view.jsf.bean.utils.LinksBean;
import com.apd.phoenix.core.PageNumberDisplay;
import com.apd.phoenix.core.PageNumberDisplay.PageSize;
import com.apd.phoenix.service.solr.SolrServiceBean;
import com.apd.phoenix.shopping.view.jsf.bean.search.SolrQueryUtilities;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import javax.annotation.PostConstruct;
import javax.ejb.LocalBean;
import javax.ejb.Stateful;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.apache.solr.client.solrj.SolrQuery;
import org.apache.solr.client.solrj.SolrServer;
import org.apache.solr.client.solrj.SolrServerException;
import org.apache.solr.client.solrj.response.QueryResponse;
import org.apache.solr.common.SolrDocumentList;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author dcnorris
 */
@Named
@Stateful
@LocalBean
//TODO consider converting this to conversation scope
@SessionScoped
public class HomeBean implements SolrSearcher, Serializable {

    private static final long serialVersionUID = 1L;
    @Inject
    private LinksBean linksBean;
    private static final Logger logger = LoggerFactory.getLogger(HomeBean.class);
    private List<Product> featuredProductList = new ArrayList<>();
    private QueryResponse response;
    private SolrServer solr;
    private SolrQuery previousSolrQuery;
    private int previousPage;
    private PageNumberDisplay pageDisplay;
    private int numFound;
    private PageNumberDisplay.PageSize pageSize = PageNumberDisplay.PageSize.FOUR;
    @Inject
    private SolrQueryUtilities solrQueryUtilities;
    @Inject
    private SolrServiceBean solrServiceBean;

    @PostConstruct
    public void init() {
        try {
            solr = solrServiceBean.getSolrServer();
            SolrQuery solrQuery = new SolrQuery();
            solrQuery = solrQueryUtilities.addFilterByCatalogID(solrQuery);
            solrQuery.setStart(pageSize.toInt());
            solrQuery.setRows(pageSize.toInt());
            String startRange = "[" + "NOW-99YEARS" + " TO " + "NOW" + "]";
            solrQuery.add("q", "coreitemstartdate:" + startRange);
            String expireRange = "[" + "NOW+1DAY" + " TO " + "NOW+99YEARS" + "]";
            solrQuery.add("q", "coreitemexpirationdate:" + expireRange);
            Random rand = new Random();
            int value = rand.nextInt(99999);
            solrQuery.addSort("random_" + value, SolrQuery.ORDER.asc);
            response = solr.query(solrQuery);
            numFound = (int) response.getResults().getNumFound();
            previousSolrQuery = solrQuery;
            SolrDocumentList searchResultDocuments = response.getResults();
            featuredProductList = SearchUtilities.convertToProductList(searchResultDocuments);
            pageDisplay = new PageNumberDisplay(numFound);
            pageDisplay.setPageSize(pageSize);
        } catch (SolrServerException ex) {
            logger.error("Error attempting to Query Solr Index Server", ex);
        }
    }
    
    public List<Product> getFeaturedProductList() {
        if (pageDisplay.getPage() != previousPage) {
            try {
                previousPage = pageDisplay.getPage();
                previousSolrQuery.setStart((pageDisplay.getPage() - 1) * pageDisplay.getSize());
                QueryResponse updatedResponse = solr.query(previousSolrQuery);
                SolrDocumentList updatedDocList = updatedResponse.getResults();
                featuredProductList = SearchUtilities.convertToProductList(updatedDocList);
            } catch (SolrServerException ex) {
                logger.error("Error sending query to solr", ex);
            }
        }
        return featuredProductList;
    }

    public PageSize getPageSize() {
        return pageSize;
    }

    public void setPageSize(PageSize pageSize) {
        this.pageSize = pageSize;
    }

    public int getPreviousPage() {
        return previousPage;
    }

    public void setPreviousPage(int previousPage) {
        this.previousPage = previousPage;
    }

    public PageNumberDisplay getPageDisplay() {
        return pageDisplay;
    }

    public void setPageDisplay(PageNumberDisplay pageDisplay) {
        this.pageDisplay = pageDisplay;
    }

    public String getFavoritesManagementLink() {
        return linksBean.getUserFavorites()+"?showList=true";
    }

}

phoenix-shopping/src/main/java/com/apd/phoenix/shopping/view/jsf/bean/search/Product.java
package com.apd.phoenix.shopping.view.jsf.bean.search;

import java.io.UnsupportedEncodingException;
import java.math.BigDecimal;
import java.net.URLEncoder;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import com.apd.phoenix.core.StringEscape;
import org.apache.commons.lang.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Presentation layer wrapper for storing product data pulled from solr results
 * or db directly
 *
 * @author dcnorris
 */
public class Product {

    private static final Logger logger = LoggerFactory.getLogger(Product.class);

    private Long id;
    private String name;
    private String description;
    private String customerSku;
    private String apdSku;
    private String manufacturerSku;
    private String vendorSku;
    private String vendorName;
    private Map<String, String> skuMap = new HashMap<>();
    private String manufacturerName;
    private String mainImageUrl;
    private Set<String> imageUrls = new HashSet<>();
    private Map<String, String> iconMap = new HashMap<>();
    private Map<String, String> properties = new HashMap<>();
    private BigDecimal price;
    private String units;
    private Date coreItemStartDate;
    private Date coreItemExpirationDate;
    static final String DETAILS_PAGE_BASE_URL = "/shopping/ecommerce/product/productDetails.xhtml";
    private String status;
    private Integer multiple;
    private Integer minimum;
    private String customerReplacementSku;
    private String customerReplacementVendor;
    private String specialOrder;
    private String customOrder;
    private static final String URL_ENCODING = "UTF-8";

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public Map<String, String> getSkuMap() {
        return skuMap;
    }

    public void setSkuMap(HashMap<String, String> skuMap) {
        this.skuMap = skuMap;
    }

    public String getManufacturerName() {
        return manufacturerName;
    }

    public void setManufacturerName(String manufacturerName) {
        this.manufacturerName = manufacturerName;
    }

    public String getMainImageUrl() {
        return mainImageUrl;
    }

    public void setMainImageUrl(String mainImageUrl) {
        this.mainImageUrl = mainImageUrl;
    }

    public Set<String> getImageUrls() {
        return imageUrls;
    }

    public void setImageUrls(Set<String> imageUrls) {
        this.imageUrls = imageUrls;
    }

    public String getCustomerSku() {
        return customerSku;
    }

    public void setCustomerSku(String customerSku) {
        this.customerSku = customerSku;
    }

    public String getUnits() {
        return units;
    }

    public void setUnits(String units) {
        this.units = units;
    }

    public String getApdSku() {
        return apdSku;
    }

    public void setApdSku(String apdSku) {
        this.apdSku = apdSku;
    }

    public String getManufacturerSku() {
        return manufacturerSku;
    }

    public void setManufacturerSku(String manufacturerSku) {
        this.manufacturerSku = manufacturerSku;
    }

    public String getVendorSku() {
        return vendorSku;
    }

    public void setVendorSku(String vendorSku) {
        this.vendorSku = vendorSku;
    }

    public String getVendorName() {
        return vendorName;
    }

    public void setVendorName(String vendorName) {
        this.vendorName = vendorName;
    }

    public Map<String, String> getIconMap() {
        return iconMap;
    }

    public void setIconMap(Map<String, String> iconMap) {
        this.iconMap = iconMap;
    }

    public Date getCoreItemStartDate() {
        return coreItemStartDate;
    }

    public void setCoreItemStartDate(Date coreItemStartDate) {
        this.coreItemStartDate = coreItemStartDate;
    }

    public Date getCoreItemExpirationDate() {
        return coreItemExpirationDate;
    }

    public void setCoreItemExpirationDate(Date coreItemExpirationDate) {
        this.coreItemExpirationDate = coreItemExpirationDate;
    }

    public Map<String, String> getProperties() {
        return properties;
    }

    public void setProperties(Map<String, String> properties) {
        this.properties = properties;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getDetailsLink() {
        StringBuilder url = new StringBuilder(DETAILS_PAGE_BASE_URL);
        if (StringUtils.isBlank(apdSku) || StringUtils.isBlank(vendorName)) {
        	return url.toString();
        }
        url.append("?");
        url.append("apdSku=");
        url.append(StringEscape.escapeForUrl(apdSku));
        url.append("&");
        url.append("vendorName=");
        url.append(StringEscape.escapeForUrl(vendorName));
        return url.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (that instanceof Product) {
            that = (Product) that;
            if (this.getId() != null) {
                return this.getId().equals(((Product) that).getId());
            }
            return super.equals(that);
        }
        else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        if (id != null) {
            return id.hashCode();
        }
        return super.hashCode();
    }

    public boolean isCoreItem() {
        if (coreItemStartDate == null || coreItemExpirationDate == null) {
            return false;
        }
        Date date = new Date();
        if (coreItemStartDate.before(date) && coreItemExpirationDate.after(date)) {
            return true;
        }
        return false;
    }

    public static String getDETAILS_PAGE_BASE_URL() {
        return DETAILS_PAGE_BASE_URL;
    }

    public Integer getMultiple() {
        return multiple;
    }

    public void setMultiple(Integer multiple) {
        this.multiple = multiple;
    }

    public Integer getMinimum() {
        return minimum;
    }

    public void setMinimum(Integer minimum) {
        this.minimum = minimum;
    }

    public String getCustomerReplacementSku() {
        return customerReplacementSku;
    }

    public void setCustomerReplacementSku(String customerReplacementSku) {
        this.customerReplacementSku = customerReplacementSku;
    }

    public String getCustomerReplacementVendor() {
        return customerReplacementVendor;
    }

    public void setCustomerReplacementVendor(String customerReplacementVendor) {
        this.customerReplacementVendor = customerReplacementVendor;
    }

    public String getSpecialOrder() {
        return specialOrder;
    }

    public void setSpecialOrder(String specialOrder) {
        this.specialOrder = specialOrder;
    }

    public String getCustomOrder() {
        return customOrder;
    }

    public void setCustomOrder(String customOrder) {
        this.customOrder = customOrder;
    }

    /**
     * Returns the customerReplacementSku specified on the CatalogXItem if one exists. If not,
     * returns the APD sku of the item specified by item.replacement.
     * @return 
     */
    public String getReplacementSku() {
        String toReturn = null;
        if (properties != null) {
            toReturn = properties.get("customerReplacementSku");
        }
        if (StringUtils.isBlank(toReturn)) {
            toReturn = customerReplacementSku;
        }
        return toReturn;
    }

    /**
     * Returns the customerReplacementVendor specified on the CatalogXItem if one exists. If not,
     * returns the vendor of the item specified by item.replacement.
     * @return 
     */
    public String getReplacementVendor() {
        String toReturn = null;
        if (properties != null) {
            toReturn = properties.get("customerReplacementVendor");
        }
        if (StringUtils.isBlank(toReturn)) {
            toReturn = customerReplacementVendor;
        }
        return toReturn;
    }

}

phoenix-shopping/src/main/webapp/ecommerce/home.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                xmlns:rich="http://richfaces.org/rich"
                xmlns:a4j="http://richfaces.org/a4j"
                xmlns:apd="http://java.sun.com/jsf/composite/apd"
                template="/WEB-INF/templates/ecommerceHomeTemplate.xhtml">
    <f:metadata>
        <f:event type="preRenderView" listener="#{favoritesBean.refreshPage()}"  />
    </f:metadata>
    <ui:define name="page_content">
        <div class="row apdMarginTop container home">
            <div class="span2">
                <ui:include src="/WEB-INF/templates/category/categoryMenu.xhtml">
                    <ui:param name="bean" value="#{productBrowseBean}" />
                    <ui:param name="listMenuItems" value="highLevelNodes" />
                </ui:include>
                <ui:include src="/WEB-INF/components/inserts/search/inkTonerCore.xhtml" />
            </div>
            <h:form id="homePageForm">
                <div class="span10 mobileHide">
                    <div class="row-fluid FeaturedWidth">
                        <div class="span12">
                            <div id="featuredProductBlock">
                                <h2>
                                    #{display['home.featured']}
                                </h2>
                                <h:panelGroup id="coreProductWidget" layout="block" styleClass="row-fluid sectionBorders">
                                    <a4j:repeat rowKeyVar="index" var="product" value="#{homeBean.featuredProductList}">
                                        <div class="span3 featured-product">
                                            <div>
                                                <a href="#{product.detailsLink}" class="thumbnail">
                                                    <img src="#{product.mainImageUrl}" alt="Image" class="crop153by153"/>
                                                </a>
                                            </div>
                                            <div class="product-info">
                                                <div class="title" style="word-break: break-word"><a href="#{product.detailsLink}">#{product.name}</a></div>
                                                <div class="manufacturer">#{product.manufacturerName}</div>
                                                <div class="sku">
                                                    <strong>SKU:</strong>#{product.customerSku}
                                                </div>
                                                <div class="product-icons">
                                                    <a4j:repeat rendered="#{not empty product.iconMap.keySet()}" value="#{viewUtils.mapToList(product.iconMap)}" var="entry" rowKeyVar="index">
                                                        <img  src="#{credentialSelectionBean.getIconUrl(entry.key)}" alt="Product Icon Image" class="productIconImage" rel="tooltip" title="#{entry.value}" />
                                                    </a4j:repeat>
                                                </div>

                                                <div class="price-per-unit">
                            						<c:if test="#{!addToCarBean.isAddingPrevented(product)}">
	                                                    <h:outputText value="#{product.price}" >
	                                                        <f:convertNumber type="currency" currencySymbol="$" />
	                                                    </h:outputText>
                                                    </c:if>
                                                </div>
                                                <apd:addToCart product="#{product}" isHomePageWidget="true"/>
                                            </div>
                                        </div>
                                    </a4j:repeat>
                                </h:panelGroup>                                    
                                <apd:pagination pageDisplay="#{homeBean.pageDisplay}" render="homePageForm" />
                            </div>
                        </div>
                    </div>
                    <div class="row-fluid FeaturedWidth">
                        <div class="span12">
                            <div id="featuredProductBlock">
                                <div class="row-fluid span9">
                                    <h2 class="pull-left">Favorite Lists</h2>                                        	
                                </div>
                                <div class="row-fluid">
                                    <h:panelGroup id="favoritesWidget" styleClass="span9 favoritesCon">
                                        <table class="table" id="favoritesTable">
                                            <thead>
                                                <tr class="darkBkgrd">
                                                    <th>
                                                        List Name <i class="icon-chevron-down smallIcon"></i>
                                                    </th>
                                                    <th>
                                                        Description
                                                    </th>
                                                    <th>
                                                        Action
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <a4j:repeat rowKeyVar="index" var="list" value="#{favoritesBean.userFavoritesListsPaginated}">
                                                    <h:panelGroup rendered="#{not empty list}">
                                                        <tr>
                                                            <td>
                                                            #{list.name}
                                                            </td>
                                                            <td>
                                                            #{favoritesBean.getItemCount(list)} Total Product(s)
                                                            </td>
                                                            <td>
                                                                <a href="#{homeBean.favoritesManagementLink}" onclick='setSelectedListById(${list.id});'>
                                                                    <i class="icon-pencil smallIcon" rel="tooltip" title="Edit"/>
                                                                </a>
                                                                <a href="#{favoritesBean.getViewLink(list.name, list.id, favoritesViewBean.PERSONAL_FAVORITES_TYPE)}">
                                                                    <i class="icon-view smallIcon" rel="tooltip" title="View"/>
                                                                </a>
                                                            </td>
                                                        </tr>
                                                    </h:panelGroup>
                                                </a4j:repeat>
                                            </tbody>
                                        </table>
                                        <apd:pagination pageDisplay="#{favoritesBean.listPaginationWidget}" render="favoritesWidget" />
                                    </h:panelGroup>
                                    <div class="span3 pull-right"><img src="#{marketingImagesBean.getImageUrl('home1')}" />
                                    </div>

                                </div>
                            </div>

                        </div>                   
                    </div>
                </div>
            </h:form>
        </div>
        <div id="push"></div>
    </ui:define>

</ui:composition>