phoenix-shopping/src/main/java/com/apd/phoenix/shopping/view/jsf/bean/favorites/FavoritesBean.java
package com.apd.phoenix.shopping.view.jsf.bean.favorites;

import java.io.IOException;
import java.io.Serializable;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import javax.annotation.PostConstruct;
import javax.ejb.Stateful;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.http.HttpServletResponse;
import org.apache.commons.lang.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.apd.phoenix.core.PageNumberDisplay;
import com.apd.phoenix.core.PageNumberDisplay.PageSize;
import com.apd.phoenix.service.business.AccountXCredentialXUserBp;
import com.apd.phoenix.service.business.CatalogBp;
import com.apd.phoenix.service.business.CatalogXItemBp;
import com.apd.phoenix.service.business.FavoritesListBp;
import com.apd.phoenix.service.model.AccountXCredentialXUser;
import com.apd.phoenix.service.model.CatalogXItem;
import com.apd.phoenix.service.model.FavoritesList;
import com.apd.phoenix.shopping.view.jsf.bean.login.CredentialSelectionBean;
import com.apd.phoenix.shopping.view.jsf.bean.search.Product;
import com.apd.phoenix.shopping.view.jsf.bean.utils.LinksBean;
import com.apd.phoenix.shopping.view.jsf.bean.utils.ViewUtils;
import com.google.gson.Gson;

/**
 *
 * @author Red Hat Consulting
 */
@Named
@Stateful
//TODO change the scoping of this bean
@SessionScoped
public class FavoritesBean implements Serializable {

    private static final String URL_ENCODING = "UTF-8";
    private static final Logger logger = LoggerFactory.getLogger(FavoritesBean.class);
    private static final long serialVersionUID = 1L;
    private static final String MY_FAVORITES_VIEW_LINK = "/shopping/ecommerce/product/favoritesView.xhtml";
    private static final String FAVORITES_LIST_PARAM = "favoritesListName";
    private static final String FAVORITES_TYPE_PARAM = "favoritesType";
    private static final String FAVORITES_ID_PARAM = "favoritesId";
    private String favoritesListName;
    private FavoritesList selectedList;
    private List<CatalogXItem> selectedListItems;
    private String selectedFavoritesListName;
    private AccountXCredentialXUser user;
    @Inject
    private FavoritesListBp favoritesListBp;
    @Inject
    private AccountXCredentialXUserBp accountXCredentialXUserBp;
    @Inject
    private CredentialSelectionBean credentialSelectionBean;
    @Inject
    private CatalogXItemBp catalogXItemBp;
    @Inject
    private CatalogBp catalogBp;
    private String newListName;
    private String errorMessage;
    private String jsonResponse;
    private List<FavoritesList> userFavoritesLists;
    private List<FavoritesList> companyFavoritesLists;
    private Map<Long, Integer> listSizes;
    private PageNumberDisplay listPaginationWidget;
    private int previousFavoritesListPage;
    private PageSize pageSize = PageSize.FIVE;
    private PageNumberDisplay itemPaginationWidget;
    private int previousListItemPage;
    private PageSize itemPageSize = PageSize.TEN;
    private long accountId;
    private long credentialId;
    private List<String> favoriteListNames;
    private Long selectedListId;
    @Inject
    private ViewUtils viewUtils;
    @Inject
    private FavoritesViewBean favoritesViewBean;
    @Inject
    private LinksBean linksBean;

    @PostConstruct
    public void init() {
        accountId = credentialSelectionBean.getCurrentAXCXU().getId();
        user = accountXCredentialXUserBp.getUserForFavoritesManagement(accountId);
        credentialId = credentialSelectionBean.getCurrentCredential().getId().longValue();
        initializePagination();
        favoriteListNames = accountXCredentialXUserBp.getFavoritesListNames(accountId);
        companyFavoritesLists = catalogBp.getFavoritesLists(credentialId);
        updateUserFavoritesList();
    }

    public void updateUserFavoritesList() {
        userFavoritesLists = accountXCredentialXUserBp.getInitializedFavoritesLists(accountId);
        listSizes = new HashMap<>();
    }

    public void refreshPage() {
        if (!allRequestParametersEmpty()) {

        }
        else if (!FacesContext.getCurrentInstance().isPostback()) {
            selectedList = null;
            errorMessage = "";
            newListName = "";
            initializePagination();
        }
        int start = (listPaginationWidget.getPage() - 1) * listPaginationWidget.getSize();
        userFavoritesLists = accountXCredentialXUserBp.getInitializedFavoritesLists(accountId, start, pageSize.toInt());
    }

    public void checkPermission() {
        if (!credentialSelectionBean.hasPermission("shopping maintain user favorites")) {
            try {
                HttpServletResponse response = (HttpServletResponse) FacesContext.getCurrentInstance()
                        .getExternalContext().getResponse();
                response.sendError(HttpServletResponse.SC_FORBIDDEN);
                return;
            }
            catch (IOException e) {
                //do nothing
            }
        }
    }

    public void initializePagination() {
        int numFound = accountXCredentialXUserBp.getFavoritesListCount(accountId);
        listPaginationWidget = new PageNumberDisplay(numFound);
        listPaginationWidget.setPageSize(pageSize);
        int start = (listPaginationWidget.getPage() - 1) * listPaginationWidget.getSize();
        userFavoritesLists = accountXCredentialXUserBp.getInitializedFavoritesLists(accountId, start, pageSize.toInt());
        previousFavoritesListPage = 0;
    }

    public void updatePagination() {
        int currentPage = listPaginationWidget.getPage();
        int numFound = accountXCredentialXUserBp.getFavoritesListCount(accountId);
        listPaginationWidget = new PageNumberDisplay(numFound);
        listPaginationWidget.setPageSize(pageSize);
        listPaginationWidget.setPage(currentPage);
        int start = (listPaginationWidget.getPage() - 1) * listPaginationWidget.getSize();
        userFavoritesLists = accountXCredentialXUserBp.getInitializedFavoritesLists(accountId, start, pageSize.toInt());
        previousFavoritesListPage = 0;
    }

    public String getViewLink(String favoritesListName, long id, String favortitesListType) {
        String browseLink = linksBean.getBrowse();
        try {
            if (favoritesViewBean.isPersonalFavoritesType(favortitesListType)) {
                browseLink = MY_FAVORITES_VIEW_LINK + "?" + FAVORITES_LIST_PARAM + "="
                        + URLEncoder.encode(favoritesListName, URL_ENCODING) + "&" + FAVORITES_TYPE_PARAM + "="
                        + URLEncoder.encode(favortitesListType, URL_ENCODING);
            }
            if (favoritesViewBean.isCompanyFavoritesType(favortitesListType)) {
                browseLink = linksBean.getBrowse() + "?" + FAVORITES_ID_PARAM + "="
                        + URLEncoder.encode((id == 0 ? "" : id + ""), URL_ENCODING) + "&" + FAVORITES_LIST_PARAM + "="
                        + URLEncoder.encode(favoritesListName, URL_ENCODING);
            }
        }
        catch (UnsupportedEncodingException e) {
            logger.error("Unable to encode favorites list name in URL: " + favoritesListName);
            logger.debug("Error", e);
        }
        return browseLink;
    }

    public void saveSelectedList() {
    	logger.info("Updating the selected list");
        selectedList = favoritesListBp.update(selectedList);
        logger.info("Loading the selected list");
        selectedList = favoritesListBp.getHydratedFavoritesList(selectedList);
        selectedListItems = new ArrayList<>(favoritesListBp.getInitializedSet(selectedList.getId()));
    }

    /**
     * Returns a subset of userFavoritesLists corresponding to the page of the list being viewed as determined by listPaginationWidget.
     * Use this method in contexts with pages.
     * 
     * @return paginated userFavoritesLists
     */
    public List<FavoritesList> getUserFavoritesListsPaginated() {
        if (listPaginationWidget.getPage() != previousFavoritesListPage) {
            previousFavoritesListPage = listPaginationWidget.getPage();
            int start = (listPaginationWidget.getPage() - 1) * listPaginationWidget.getSize();
            userFavoritesLists = accountXCredentialXUserBp.getInitializedFavoritesLists(accountId, start, pageSize
                    .toInt());
            selectedList = null;
        }
        return userFavoritesLists;
    }

    /**
     * Returns the entire userFavoritesLists
     * 
     * @return userFavoritesLists
     */
    public List<FavoritesList> getAllUserFavoritesLists() {
        userFavoritesLists = accountXCredentialXUserBp.getInitializedFavoritesLists(accountId);
        return userFavoritesLists;
    }

    public List<FavoritesList> getCompanyFavoritesLists() {
        return companyFavoritesLists;
    }

    public FavoritesList getSelectedList() {
        return this.selectedList;
    }

    public void setSelectedList(FavoritesList selectedList) {
    	if (selectedList == null) {
    		return;
    	}
        this.selectedList = favoritesListBp.getHydratedFavoritesList(selectedList);
        int numFound = favoritesListBp.getListItemCount(selectedList.getId());
        itemPaginationWidget = new PageNumberDisplay(numFound);
        itemPaginationWidget.setPageSize(itemPageSize);
        int start = (itemPaginationWidget.getPage() - 1) * itemPaginationWidget.getSize();
        selectedListItems = new ArrayList<>(favoritesListBp.getInitializedSet(selectedList.getId(),start, itemPageSize.toInt()));
    }

    public void setSelectedListById() {
        if (this.selectedListId == null) {
            return;
        }
        FavoritesList list = this.favoritesListBp.findById(selectedListId, FavoritesList.class);

phoenix-shopping/src/main/java/com/apd/phoenix/shopping/view/jsf/bean/product/Breadcrumb.java
package com.apd.phoenix.shopping.view.jsf.bean.product;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.ArrayList;
import java.util.List;
import org.apache.commons.lang.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author dcnorris
 */
public class Breadcrumb {

    private static final Logger logger = LoggerFactory.getLogger(Breadcrumb.class);
    private static final String SEARCH_PAGE_BASE_URL = "/shopping/ecommerce/product/browse.xhtml";
    private static final String HIERARCHY_DELIMITER = "!";
    private static final String HIERARCHY_PATH_PARAMETER = "hierarchyPath";
    private List<String> crumbs;
    private String tail;

    public Breadcrumb() {
    }

    public Breadcrumb(String hierarchyPath) {
        if (StringUtils.isNotBlank(hierarchyPath)) {
            parseHierarchyPath(hierarchyPath);
        }
    }

    private void parseHierarchyPath(String hierarchyPath) {
        logger.debug("Info from parseHierarchyPath(), before Parsing of hierarchyPath: " + hierarchyPath);
        String[] pathTokens = hierarchyPath.substring(1, hierarchyPath.length()).split(HIERARCHY_DELIMITER);
        crumbs = new ArrayList<>();
        for (String token : pathTokens) {
            logger.debug("Added to breadcrumb list:" + token);
            crumbs.add(token);
        }
        //Store Tail
        tail = crumbs.get(crumbs.size() - 1);
        //Remove tail
        crumbs.remove(crumbs.size() - 1);
    }

    public List<String> getCrumbs() {
        if (crumbs == null) {
            return new ArrayList<>();
        }
        return crumbs;
    }

    public String getCrumbURL(String crumb) {
        StringBuilder url = new StringBuilder(SEARCH_PAGE_BASE_URL);
        try {
            int index = crumbs.indexOf(crumb) + 1;
            url.append("?").append(HIERARCHY_PATH_PARAMETER);
            url.append("=");
            for (int i = 0; i < index; i++) {
                url.append(HIERARCHY_DELIMITER).append(URLEncoder.encode(crumbs.get(i), "UTF-8"));
            }
        }
        catch (UnsupportedEncodingException ex) {
            logger.error("Error url decoding hierarchy path string", ex);
        }
        return url.toString();
    }

    public void setCrumbs(List<String> crumbs) {
        this.crumbs = crumbs;
    }

    public String getTail() {
        return tail;
    }
}

phoenix-shopping/src/main/java/com/apd/phoenix/shopping/view/jsf/bean/product/DepartmentValidator.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.apd.phoenix.shopping.view.jsf.bean.product;

import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.validator.FacesValidator;
import javax.faces.validator.Validator;
import javax.faces.validator.ValidatorException;
import org.apache.commons.lang.StringUtils;
import com.apd.phoenix.shopping.view.jsf.bean.user.UserMaintenanceBean;

/**
 *
 * @author zgutterm
 */
@FacesValidator("departmentValidator")
public class DepartmentValidator implements Validator {

    public static final String THIS_FIELD_IS_REQUIRED = "This field is required";

    @Override
    public void validate(FacesContext context, UIComponent component, Object value) throws ValidatorException {
        //Cannot inject a bean in a JSF validator
        UserMaintenanceBean userMaintenanceBean = context.getApplication().evaluateExpressionGet(context,
                "#{userMaintenanceBean}", UserMaintenanceBean.class);

        if (userMaintenanceBean.isDepartmentListEmpty()) {
            if (!(value instanceof String) || (String) value == null || StringUtils.isEmpty((String) value)) {
                throw new ValidatorException(new FacesMessage(THIS_FIELD_IS_REQUIRED));
            }
        }
    }
}

phoenix-shopping/src/main/java/com/apd/phoenix/shopping/view/jsf/bean/product/EmailFieldValidator.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.apd.phoenix.shopping.view.jsf.bean.product;

import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.validator.FacesValidator;
import javax.faces.validator.Validator;
import javax.faces.validator.ValidatorException;
import org.apache.commons.validator.EmailValidator;

/**
 *
 * @author nreidelb
 */
@FacesValidator("emailFieldValidator")
public class EmailFieldValidator implements Validator {

    @Override
    public void validate(FacesContext fc, UIComponent uic, Object inputEmail) throws ValidatorException {
        String email = (String) inputEmail;
        if (email == null) {
            throw new ValidatorException(new FacesMessage("Please enter a valid email address"));
        }
        EmailValidator eValidator = EmailValidator.getInstance();
        if (!eValidator.isValid(email)) {
            throw new ValidatorException(new FacesMessage("Please enter a valid email address"));
        }
    }

}

phoenix-shopping/src/main/java/com/apd/phoenix/shopping/view/jsf/bean/product/NovantEmailValidator.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.apd.phoenix.shopping.view.jsf.bean.product;

import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.validator.FacesValidator;
import javax.faces.validator.Validator;
import javax.faces.validator.ValidatorException;
import com.apd.phoenix.shopping.view.jsf.bean.PageCssBean;
import com.apd.phoenix.shopping.view.jsf.bean.login.LoginBean;

/**
 *
 * @author zgutterm
 */
//TODO Refactor organization email validators into one class
@FacesValidator("novantEmailValidator")
public class NovantEmailValidator implements Validator {

    public static final String PLEASE_ENTER_A_VALID_EMAIL_ADDRES = "Please enter an email address valid to your organization.";

    @Override
    public void validate(FacesContext context, UIComponent component, Object value) throws ValidatorException {
        //Cannot inject a bean in a JSF validator
        LoginBean loginBean = context.getApplication().evaluateExpressionGet(context, "#{loginBean}", LoginBean.class);
        PageCssBean pageCssBean = context.getApplication().evaluateExpressionGet(context, "#{pageCssBean}",
                PageCssBean.class);
        if (!(value instanceof String)) {
            throw new ValidatorException(new FacesMessage(PLEASE_ENTER_A_VALID_EMAIL_ADDRES));
        }
        if (loginBean.getIsNovantSubdomain()) {
            if (!loginBean.validEmailAddress((String) value, pageCssBean.getSubdomainValue())) {
                throw new ValidatorException(new FacesMessage(PLEASE_ENTER_A_VALID_EMAIL_ADDRES));
            }
        }
    }
}

phoenix-shopping/src/main/java/com/apd/phoenix/shopping/view/jsf/bean/product/SortOption.java
package com.apd.phoenix.shopping.view.jsf.bean.product;

/**
 *
 * @author dcnorris
 */
public enum SortOption {

    ALPHABETICAL("Product name A - Z"), REVERSE_ALPHABETICAL("Product name Z - A"), PRICE_LOWEST("Price Lowest first"), PRICE_HIGHEST(
            "Price Highest first");

    private String label;

    private SortOption(String label) {
        this.label = label;
    }

    public String getLabel() {
        return label;
    }
}

phoenix-shopping/src/main/webapp/ecommerce/product/favorites.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                xmlns:rich="http://richfaces.org/rich"
                xmlns:a4j="http://richfaces.org/a4j"
                template="/WEB-INF/templates/ecommerceFavoriteProductListTemplate.xhtml"
                xmlns:apd="http://java.sun.com/jsf/composite/apd">
    <f:metadata>
        <f:event type="preRenderView" listener="#{favoritesBean.refreshPage()}"  />
        <f:event type="preRenderView" listener="#{favoritesBean.checkPermission()}"  />
    </f:metadata>
    <ui:define name="page_content">
        <h:form id="listsForm">
            <div class="row apdCenter container">	
                <div class="span6 shoppoingCart-Header">
                    <h3>#{display['favorites.my.title']}</h3>
                </div>
            </div>
            <div class="row apdCenter container">	
                <div class="row-fluid">
                    <div class="span12 mobileHide">
                        <div class="pull-right">
                        <!-- 
                            <h:panelGroup rendered="#{not empty favoritesBean.errorMessage}">
                                <span class="help-inline sortByLabel">
                                    <i class="icon-info-sign" rel="tooltip" title="Error"/>
                                    <h:outputText class="error-text"
                                                  value="#{favoritesBean.errorMessage}"/>
                                    #{display['favorites.listName']}
                                </span>
                            </h:panelGroup>
                            <h:inputText value="#{favoritesBean.newListName}"/>
                          -->
                            <h:commandLink styleClass="smallBtn" value="View All" action="#{favoritesBean.getAllUserFavoritesLists()}"/>
                        </div>
                    </div>
                    <div class="span12 fl-wrapper">
                        <div class="span12 fl-container">
                            <div class="span12 divInside-Fade">
                                <h5>#{display['favorites.favoriesList']}</h5>
                            </div>

                            <div class="span12 headerBkgrd-pd mobileHide">
                                <div class="span3"><h4>List Name</h4></div>
                                <div class="span5"><h4>Product(s)</h4></div>
                                <div class="span2"><h4> </h4></div>
                                <div class="span2 pull-right"><h4>Actions</h4></div>
                                <div class="clearfix"></div>
                            </div>
                            <a4j:repeat rowKeyVar="index" rendered="#{not empty favoritesBean.userFavoritesListsPaginated}" var="list" 
                                                                      value="#{favoritesBean.userFavoritesListsPaginated}">
                                <h:panelGroup rendered="#{favoritesBean.getItemCount(list) >= 0}" styleClass="#{index % 2 == 0 ? 'whiteBkgrd-pd' : 'grayBkgrd-pd'} span12">
                                    <div class="span3 listNameField">
                                        <p>
                                            <a href="#{favoritesBean.getViewLink(list.name, list.id, favoritesViewBean.PERSONAL_FAVORITES_TYPE)}">#{list.name}</a>
                                        </p>
                                    </div>
                                    <div class="span5"><p>#{favoritesBean.getItemCount(list)} Total Product(s)</p></div>
                                    <div class="span2"><p></p></div>
                                    <div class="span2 pull-right actionContainer">
                                        <a4j:commandLink render="listsForm" action="#{favoritesBean.setSelectedList(list)}">
                                            <i class="icon-pencil smallIcon" rel="tooltip" title="Edit"/>
                                        </a4j:commandLink>
                                        <a href="#{favoritesBean.getViewLink(list.name, list.id, favoritesViewBean.PERSONAL_FAVORITES_TYPE)}">
                                            <i class="icon-view smallIcon" rel="tooltip" title="View"/>
                                        </a>
                                        <a href="#confirmListDelete" onclick='setSelectedListById(${list.id});' data-toggle="modal">
                                            <i class="icon-trash smallIcon" rel="tooltip" title="Delete List"/>
                                        </a>              
                                    </div>
                                    <div class="clearfix"></div>
                                </h:panelGroup>
                            </a4j:repeat>
                        </div>
                        <apd:pagination pageDisplay="#{favoritesBean.listPaginationWidget}" render="listsForm" /> 
                    </div>      
                </div>
                <div class="row-fluid">
                    <h:panelGroup id="listsSummary" rendered="#{not empty favoritesBean.selectedList and favoritesBean.selectedList!=null}" layout="block" styleClass="span12 fl-wrapper">
                        <div class="span12 fl-container">
                            <div class="span12 divInside-Fade">
                                <h5>#{display['favorites.modify']}</h5>
                            </div>

                            <div class="span12 borderBottom">
                                <div class="span6 inline">
                                    <h4>#{display['favorites.favoritesListName']}</h4>
                                    <h:inputText id="listName" styleClass="input-medium search-query" value="#{favoritesBean.selectedList.name}" />
                                    <a4j:commandLink value="SAVE" render="listsForm" styleClass="smallBtn" action="#{favoritesBean.saveSelectedList}"/>
                                </div>

                                <div class="span2 pull-right">                                
                                    <a href="#confirmListDelete" class="btn btn-primary" onclick='setSelectedListById(${favoritesBean.selectedList.id});' data-toggle="modal">
                                                #{display['favorites.deleteList']}
                                    </a> 
                                </div>
                                <div class="clearfix"></div>
                            </div>

                            <div class="span12" style="padding:10px">
                                <a4j:repeat id="itemListBlock" rowKeyVar="index" var="product" value="#{favoritesBean.selectedListItems}">
                                    <!-- ==== PRODUCT 1 ==== -->            
                                    <h:panelGroup rendered="#{not empty product}" styleClass="row-fluid show-grid">
                                        <!-- IMAGE -->
                                        <div class="span1 mobilePic">
                                            <a href="#{favoritesBean.getProductDetailURL(product)}">
                                                <img src="#{product.mainImageUrl}"/>
                                            </a>
                                        </div>

                                        <!-- DESC -->  
                                        <div class="span5 mobileRight">
                                            <p class="product-title"><a href="#{favoritesBean.getProductDetailURL(product)}">#{product.name}</a></p>
                                            <p class="product-man">#{product.manufacturerName}</p>
                                            <p class="product-sku"><strong>SKU:</strong> #{product.customerSku}</p>
                                        </div>

                                        <!-- FEATURED -->      
                                        <div class="span2 mobileRight">
                                            <div>
                                                <a4j:repeat rendered="#{not empty product.iconMap.keySet()}" value="#{viewUtils.mapToList(product.iconMap)}" var="entry" rowKeyVar="index">
                                                    <img  src="#{credentialSelectionBean.getIconUrl(entry.key)}" alt="Product Icon Image" class="productIconImage" rel="tooltip" title="#{entry.value}" />
                                                </a4j:repeat>
                                            </div>
                                        </div>
                                        <!-- PRICE -->    
                                        <div class="span1 mobileRight">
                                            <p class="product-price">
                                                <h:outputText value="#{product.price}">
                                                    <f:convertNumber type="currency" currencySymbol="$" />
                                                </h:outputText>
                                            </p>
                                        </div>
                                        <!-- UNITS -->
                                        <div class="span1 mobileRight">
                                            <p class="product-units">#{product.units}</p>
                                        </div>

                                        <!-- REMOVE -->    
                                        <div class="span3 removeList pull-right">
                                            <p>#{display['favorites.remove']} 
                                                <a4j:commandLink render="@all" styleClass="btn btn-small btnRed btnRemove" action="#{favoritesBean.removeFromSelectedList(product)}">
                                                    <i class="icon-remove icon-white" rel="tooltip" title="Delete Item"/>
                                                </a4j:commandLink>
                                            </p>
                                        </div>                
                                    </h:panelGroup>
                                    <!-- ==== PRODUCT END ==== --> 
                                </a4j:repeat>        
                            </div>

                            <div class="span12">

                            </div>
                        </div>
                        <apd:pagination pageDisplay="#{favoritesBean.itemPaginationWidget}" render="listsSummary" />
                    </h:panelGroup>     
                </div>
            </div>
        </h:form>     
         <div id="confirmListDelete" class="modal hide fade" tabindex="-1" role="dialog"
			aria-labelledby="myModalLabel" aria-hidden="true">
            <h:form id="modalForm1">
                    <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal"
                                    aria-hidden="true">×</button>
                            <h3 id="myModalLabel">#{display['favorites.confirm']}</h3>
                    </div>
                    <div class="modal-body">
                        <h:outputLabel value="#{display['favorites.confirmQuestion']}" />
                    </div>
                    <div class="modal-footer">
                        <h:commandButton value="Yes" action="#{favoritesBean.removeSelectedList}" styleClass="btn btn-primary">
                            <f:ajax execute="@form" onevent="modalEventHandler"/>
                        </h:commandButton>
                        <h:commandButton value="No" styleClass="btn btn-primary">
                            <f:ajax execute="@form" onevent="modalEventHandler"/>
                        </h:commandButton>
                    </div>
            </h:form>
       </div>
    </ui:define>

</ui:composition>